#!/bin/bash -ex
############################################################
# <bsn.cl fy=2013 v=onl>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#
# Licensed under the Eclipse Public License, Version 1.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#        http://www.eclipse.org/legal/epl-v10.html
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific
# language governing permissions and limitations under the
# License.
#
# </bsn.cl>
############################################################
#
# post-build
#
############################################################
TARGET=$1
[ -d "${TARGET}" ] || { echo "Usage: $0 TARGET_DIR" >&2; exit 1; }

ROOTFILES=$(dirname $0)/rootfiles
[ -d "${ROOTFILES}" ] || { echo "Could not find rootfiles dir" >&2; exit 1; }

# Skip these services
rm -rf "${TARGET}/etc/init.d/S01logging"
rm -rf "${TARGET}/etc/init.d/S40network"
rm -rf "${TARGET}/etc/init.d/S50dropbear"

tar -c --exclude '.*~' -C ${ROOTFILES} . | tar -xv -C ${TARGET}



